### PR TITLE
Add renv guides to update renv.lock file

### LINKED ISSUE #58: add how to update the renv.lock file to the CONTRIBUTING file
related with #50 

task: add guidance on adding new packages to the exiting renv registry

> can I add packages freely when adding a new workflow, or are there any restrictions?

yes. similar to what we do in the tutorials repos, a new PR with new packages should include the updated renv.lock file.

> should we update the whole renvlock in main first? 

probably yes? I think this would facilitate singular additions in each new PR

### PR DESCRIPTION
**Pull request by avallecam**
Fix #58

### CODE REVIEW

**Comment by avallecam** [comment]
hi @pratikunterwegs I briefly added guidelines. could we have your brief review?

**Review by pratikunterwegs — COMMENTED** [review]
Thanks @avallecam, this looks good to me. Could you also mention when to use `renv::update()` and `renv::upgrade()`, and whether that should be done in a separate PR from adding an analysis.

**Comment by avallecam** [comment]
Could you also mention when to use `renv::update()` and `renv::upgrade()`, and whether that should be done in a separate PR from adding an analysis.

Appropriate suggestion. Added in https://github.com/epiverse-trace/howto/pull/67/commits/b8ed4213ac0ee360e2ea9ea0d1440c7361d09a0d and https://github.com/epiverse-trace/howto/pull/67/commits/b89a36a65261acb276680034e4eb2fab709badaa

**Comment by pratikunterwegs** [comment]
Great thanks!

**Pull request merged**
