### PR TITLE
Update renv and lockfile

### LINKED ISSUE #50: update {howto} renv lock file

### PR DESCRIPTION
**Pull request by pratikunterwegs**
This PR fixes #50 as follows:

1. Updates renv to v1.0.7
2. Updates the renv lockfile with R v4.4.0 and new package versions.

### CODE REVIEW

**Comment by pratikunterwegs** [comment]
I'm not really sure why there's an issue with installing {StanHeaders}, will look into it.

**Comment by avallecam** [comment]
> I'm not really sure why there's an issue with installing {StanHeaders}, will look into it.

thank you for setting this up. should we wait for {StanHeaders} to update dependencies to let this PR pass all checks and merge before merging #57 or #60 right? Is it possible to estimate this update to should we re-run the workflow?

**Comment by pratikunterwegs** [comment]
Hi @avallecam, this PR is failing checks because one or more of the workflows uses the function `epiparameter::epiparam()`, which has been removed in more recent version of {epiparameter}. I'll file a separate issue for replacing this usage with `epiparameter::epidist_db()`. I would also suggest putting the render workflow on a monthly CRON job so that we know of breaking changes in packages under development.

**Comment by avallecam** [comment]
@pratikunterwegs epiparameter::epiparam() was replaced in #63 I needed to update some other packages (R.utils, arm, matrix) in order to pass all checks. Are you able to rebase and solve conflicts in this PR?

**Comment by pratikunterwegs** [comment]
I'm pushing changes to this PR after rebasing on `main` so will wait for checks to run.

**Review by avallecam — APPROVED** [review]
looks good, nothing to add, ready to merge 🚀

**Pull request merged**
